language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.0
before_script:
  - mysql -e 'create database promdash_test;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install jshint
  - npm install
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:migrate
script:
  - jshint app/assets/javascripts
  - RAILS_ENV=test bundle exec rake spec
  - RAILS_ENV=test bundle exec rake karma:run
